# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'GymNet' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GymNet
  
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Analytics'

  target 'GymNetTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GymNetUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
